Repository kubernetes-sigs/windows-service-proxy, pull requests merged in 2023-01, with the labels that each got.

#1 Initial k2s import and local-run
  Makefile
  cmd/k2s.go
  cmd/main.go
  go.mod
  go.sum
  pkg/storecmds/command_builder.go
  pkg/storecmds/storecmds_windows.go
Labels: approved, lgtm, cncf-cla: yes, size/XXL

#4 initial backend import
  Makefile
  backend/OWNERS
  backend/kernelspace/.gitignore
  backend/kernelspace/OWNERS
  backend/kernelspace/README.md
  backend/kernelspace/build.sh
  backend/kernelspace/config.go
  backend/kernelspace/cross-compile.sh
  backend/kernelspace/dualstack.go
  backend/kernelspace/endpoints.go
  backend/kernelspace/hcnutils.go
  backend/kernelspace/metrics.go
  backend/kernelspace/proxier.go
  backend/kernelspace/proxier_events.go
  backend/kernelspace/service.go
  backend/kernelspace/sink.go
  backend/kernelspace/types.go
  backend/kernelspace/util.go
  go.mod
  go.sum
  pkg/storecmds/storecmds_windows.go
Labels: approved, cncf-cla: yes, size/XXL

#5 Cross compilation and k2s module import
  OWNERS
  cmd/k2s.go
  cmd/main.go
  go.mod
  go.sum
  hack/cross-compile.sh
  pkg/storecmds/command_builder.go
  pkg/storecmds/storecmds_windows.go
Labels: approved, cncf-cla: yes, size/L

#9 Build and push kpng container image
  .github/workflows/image-build.yaml
  Dockerfile.windows
  Makefile
  cloudbuild.yaml
  hack/build_windows_container.sh
Labels: approved, lgtm, cncf-cla: yes, size/L

#14 Enabling healthz endpoint
  backend/kernelspace/.gitignore
  backend/kernelspace/build.sh
  backend/kernelspace/config.go
  backend/kernelspace/cross-compile.sh
  backend/kernelspace/proxier.go
  backend/kernelspace/sink.go
  go.mod
  go.sum
  pkg/healthcheck/common.go
  pkg/healthcheck/proxier_health.go
  pkg/healthcheck/service_health.go
Labels: approved, lgtm, cncf-cla: yes, size/XL

#15 Enabling feature gates
  backend/kernelspace/dualstack.go
  backend/kernelspace/proxier.go
  backend/kernelspace/service.go
  backend/kernelspace/sink.go
  backend/kernelspace/util.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#17 Adding metrics server and fixing k8s dependency
  .github/workflows/golangci-lint.yml
  backend/kernelspace/dualstack.go
  backend/kernelspace/endpoints.go
  backend/kernelspace/hcnutils.go
  backend/kernelspace/metrics/metrics.go
  backend/kernelspace/proxier.go
  backend/kernelspace/proxier_events.go
  backend/kernelspace/register.go
  backend/kernelspace/service.go
  backend/kernelspace/sink.go
  backend/kernelspace/types.go
  cmd/main.go
  go.mod
  go.sum
  pkg/healthcheck/service_health.go
  pkg/util/network.go
  pkg/util/util.go
Labels: approved, lgtm, cncf-cla: yes, size/XL

#19 fix sourcevip assignment in NewProxier
  backend/kernelspace/proxier.go
Labels: approved, lgtm, cncf-cla: yes, size/XS

#20 Adding internal traffic policy work
  backend/kernelspace/proxier.go
  backend/kernelspace/proxier_events.go
  backend/kernelspace/service.go
  backend/kernelspace/sink.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#21 fixing push-image job
  Makefile
Labels: approved, lgtm, cncf-cla: yes, size/XS

#22 explicitly set DOCKER_CLI_EXPERIMENTAL=enabled build_windows-container.sh
  hack/build_windows_container.sh
Labels: approved, lgtm, cncf-cla: yes, size/XS

#23 Updating cloudbuild.yaml to use a container image that buildx support
  cloudbuild.yaml
Labels: approved, lgtm, cncf-cla: yes, size/XS

#29 Cloudbuild fixups
  cloudbuild.yaml
  hack/build_windows_container.sh
Labels: approved, lgtm, size/M, cncf-cla: yes

#25 Adding deployment files for running on capz with calico CNI
  Dockerfile.windows
  backend/kernelspace/hcnutils.go
  deploy/kpng-rbac.yaml
  deploy/kpng-windows-capz-calico.yaml
  deploy/start-kpng.ps1
Labels: approved, lgtm, cncf-cla: yes, size/L
